name: inmobiliaria
services:
  db:
    image: mariadb:11.3.2
    container_name: inmobiliaria-db
    environment:
      MYSQL_USER: $MARIADB_USER
      MYSQL_PASSWORD: $MARIADB_PASSWORD
      MYSQL_DATABASE: $MARIADB_DATABASE
      MYSQL_PORT: 3306,
      MYSQL_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - /home/astable/mariadb_data:/var/lib/mysql